"""Create explicitly synthetic pseudo-probe fixtures (never measured data)."""
from __future__ import annotations

import json
from pathlib import Path
import sys
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from roast_solver import BoundaryConditions, SolverConfig, simulate_preset

CASES = [
    {"name": "synthetic-roast-still-open", "preset": "roast", "mass_kg": 0.6, "oven_c": 170.0, "h_conv_w_m2k": 10.0, "emissivity": 0.90, "moisture_kg_m2": 0.25, "covered": False},
    {"name": "synthetic-slab-fan-covered", "preset": "slab", "mass_kg": 0.6, "oven_c": 170.0, "h_conv_w_m2k": 20.0, "emissivity": 0.90, "moisture_kg_m2": 0.25, "covered": True},
]
output = {"schema": 1, "provenance": "synthetic/generated by NumPy reference; no empirical observations", "grid_size": 21, "fixtures": []}
for case in CASES:
    bc = BoundaryConditions(
        ambient_c=case["oven_c"], wall_c=case["oven_c"], h_conv=case["h_conv_w_m2k"],
        emissivity=case["emissivity"], relative_humidity=0.98 if case["covered"] else 0.15,
        covered=case["covered"], moisture_reservoir_kg_m2=case["moisture_kg_m2"],
    )
    config = SolverConfig(initial_c=10, target_c=200, oven=bc, max_cook_s=1800, rest_s=0, sample_interval_s=300)
    result = simulate_preset(case["preset"], case["mass_kg"], 21, config)
    fixture = dict(case)
    fixture["samples"] = [{"time_s": round(p.time_s, 3), "probe_c": round(p.probe_c, 5), "coldest_c": round(p.coldest_c, 5)} for p in result.history]
    output["fixtures"].append(fixture)
path = Path(__file__).with_name("synthetic_calibration.json")
path.write_text(json.dumps(output, indent=2) + "\n")
print(path)
