"""Regenerate Rust/WASM golden anchors from the authoritative NumPy solver."""
from __future__ import annotations

import csv
from pathlib import Path
import sys
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from roast_solver import BoundaryConditions, SolverConfig, simulate_preset

CASES = [
    ("roast-still-open", "roast", 0, False, False),
    ("slab-fan-covered", "slab", 2, True, True),
    ("bird-fan-open", "bird", 1, True, False),
]

rows = []
for name, preset, preset_id, fan, covered in CASES:
    config = SolverConfig(
        initial_c=10, target_c=200,
        oven=BoundaryConditions.oven(170, fan, covered),
        max_cook_s=1800, rest_s=0, sample_interval_s=1800,
    )
    result = simulate_preset(preset, 0.6, 21, config)
    point = result.history[-1]
    rows.append([name, preset_id, 0.6, 170, 10, int(fan), int(covered), 21, 1800,
                 point.coldest_c, point.probe_c, point.hottest_c,
                 point.pasteurization_minutes, result.evaporated_kg])

path = Path(__file__).with_name("wasm_golden.csv")
with path.open("w", newline="") as stream:
    stream.write("# Generated by fixtures/generate_golden.py with the NumPy reference; temperatures C, pasteurization minutes, mass kg\n")
    writer = csv.writer(stream)
    writer.writerow("name preset mass_kg oven_c initial_c convection covered n duration_s coldest_c probe_c hottest_c pasteurization_min evaporated_kg".split())
    writer.writerows(rows)
print(path)
