#!/usr/bin/env python3
"""Regenerate deterministic *synthetic* fixture curves from the NumPy oracle."""
import json
import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from roast_solver.geometry import make_geometry
from roast_solver.solver import simulate_roast

SCENARIOS=[
 dict(id="roast-still-uncovered",preset="roast",mass_kg=.75,oven_c=160.,initial_c=10.,target_c=35.,convection=False,covered=False),
 dict(id="slab-fan-covered",preset="slab",mass_kg=.75,oven_c=160.,initial_c=10.,target_c=35.,convection=True,covered=True),
]
out={"schema":1,"provenance":"SYNTHETIC: generated by NumPy model; contains no probe measurements", "resolution":26,"scenarios":[]}
for item in SCENARIOS:
    g=make_geometry(item["preset"],item["mass_kg"],26)
    r=simulate_roast(g,item["initial_c"],item["oven_c"],item["target_c"],item["convection"],item["covered"],rest_minutes=5,sample_seconds=300)
    row={**item,"time_s":r.time_s.tolist(),"coldest_c":r.coldest_c.tolist(),"pull_time_s":r.pull_time_s,"peak_c":r.peak_c}
    out["scenarios"].append(row)
Path("fixtures/synthetic_calibration.json").write_text(json.dumps(out,indent=2)+"\n")
