#!/usr/bin/env python3
"""Generate dependency-light cross-language golden values from NumPy oracle."""
import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
import numpy as np
from roast_solver.properties import food_properties, radiation_coefficient
from roast_solver.solver import dirichlet_box_step, BoundaryConfig, SimulationConfig, simulate
from roast_solver.geometry import make_geometry
lines=["# Generated by Python reference; values are SI and synthetic."]
for t in (5.,60.,100.): lines.append("PROP,"+",".join(format(x,'.17g') for x in (t,*food_properties(t))))
lines.append("RAD,"+",".join(format(x,'.17g') for x in (60.,180.,.9,radiation_coefficient(60.,180.,.9))))
n=5; alpha=.01; h=.25; dt=.1
t=(np.arange(n**3,dtype=np.float32)%7).reshape((n,n,n));t[[0,-1],:,:]=0;t[:,[0,-1],:]=0;t[:,:,[0,-1]]=0
for _ in range(3):t=dirichlet_box_step(t,alpha,h,dt)
lines.append("STENCIL,"+",".join(format(x,'.17g') for x in (n,alpha,h,dt,3,t.ravel()[62],t.sum())))
g=make_geometry('roast',.25,resolution=12)
r=simulate(g,BoundaryConfig(oven_c=180),SimulationConfig(initial_c=20,target_c=30,max_cook_s=4000,rest_s=300,output_interval_s=30))
lines.append('INTEGRATION,'+','.join(format(x,'.17g') for x in (0,12,.25,180,20,30,4000,300,r.pull_time_s,r.carryover_c,r.pasteurization_equivalent_s)))
Path('fixtures/core_golden_v1.csv').write_text('\n'.join(lines)+'\n')
