#!/usr/bin/env python3
"""Regenerate the explicitly synthetic, model-to-model calibration fixture."""
import json
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from roast_solver.geometry import make_geometry
from roast_solver.solver import BoundaryConfig, SimulationConfig, simulate

scenario={"preset":"roast","mass_kg":0.25,"resolution":16,"oven_c":180.0,
          "initial_c":20.0,"target_c":30.0,"max_cook_s":3600.0,"rest_s":600.0}
g=make_geometry(scenario["preset"],scenario["mass_kg"],resolution=scenario["resolution"])
r=simulate(g,BoundaryConfig(oven_c=scenario["oven_c"]),
           SimulationConfig(initial_c=scenario["initial_c"],target_c=scenario["target_c"],
                            max_cook_s=scenario["max_cook_s"],rest_s=scenario["rest_s"],
                            output_interval_s=120))
data={"kind":"synthetic-model-output","empirical":False,
      "notice":"Generated by the reference model; not a measured probe log and not evidence of accuracy.",
      "scenario":scenario,"expected":r.summary(),
      "curve":{"time_s":r.times_s.tolist(),"probe_c":r.probe_c.tolist(),"coldest_c":r.coldest_c.tolist()}}
Path("fixtures/synthetic_roast_v1.json").write_text(json.dumps(data,indent=2)+"\n")
