"""Regenerate the dependency-free interior-kernel cross-language fixture."""
import numpy as np
from pathlib import Path

n=9; steps={0,10,25,50,100,200}; t=np.zeros((n,n,n),dtype=np.float32)
t[[0,-1],:,:]=1;t[:,[0,-1],:]=1;t[:,:,[0,-1]]=1
rows=[]
for s in range(max(steps)+1):
    if s in steps: rows.append((s,float(t[n//2,n//2,n//2])))
    if s==max(steps): break
    old=t.copy()
    t[1:-1,1:-1,1:-1]=old[1:-1,1:-1,1:-1]+np.float32(.1)*(old[2:,1:-1,1:-1]+old[:-2,1:-1,1:-1]+old[1:-1,2:,1:-1]+old[1:-1,:-2,1:-1]+old[1:-1,1:-1,2:]+old[1:-1,1:-1,:-2]-6*old[1:-1,1:-1,1:-1])
out="# Synthetic numerical fixture; n=9, r=0.1, Dirichlet faces=1, interior=0\n# Generated by scripts/generate_golden.py. This is not probe/calibration data.\nstep,center_reduced_temperature\n"+"".join(f"{s},{v:.10f}\n" for s,v in rows)
Path("fixtures/web_kernel_golden.csv").write_text(out)
