const $=s=>document.querySelector(s), form=$('#controls'), chart=$('#chart'), slice=$('#slice');
let worker=null,curve=[],field=null,currentTarget=57;
function makeWorker(){if(worker)worker.terminate();worker=new Worker('./worker.js',{type:'module'});worker.onmessage=onWorker;return worker}
function config(){const f=new FormData(form);return {preset:f.get('preset'),mass:+f.get('mass'),initial:+f.get('initial'),oven:+f.get('oven'),target:+f.get('target'),rest:+f.get('rest'),resolution:+f.get('resolution'),fan:f.has('fan'),covered:f.has('covered')}}
form.addEventListener('submit',e=>{e.preventDefault();const c=config();currentTarget=c.target;curve=[];field=null;drawChart();drawSlice();$('#run').disabled=true;$('#status').textContent='Solving…';$('#engine').textContent='loading core';$('#progress').style.width='1%';makeWorker().postMessage({type:'run',config:c})});
function onWorker({data:d}){
  if(d.type==='engine'){$('#engine').textContent=d.name;return}
  if(d.type==='progress'){curve.push(d.point);drawChart();$('#status').textContent=`${d.point.phase} · ${(d.point.t/60).toFixed(0)} min`;$('#progress').style.width=`${Math.max(2,100*d.fraction)}%`;return}
  if(d.type==='error'){$('#status').textContent='Simulation failed';$('#engine').textContent=d.message;$('#run').disabled=false;console.error(d.message);return}
  if(d.type==='done'){curve=d.curve;field={n:d.n,temperature:d.temperature,mask:d.mask};$('#run').disabled=false;$('#status').textContent='Complete';$('#progress').style.width='100%';
    $('#pull').textContent=d.pull==null?'not reached':fmtTime(d.pull);$('#peak').textContent=`${d.peak.toFixed(1)} °C`;$('#carry').textContent=d.pull==null?'target not reached':`+${Math.max(0,d.peak-currentTarget).toFixed(1)} °C carryover`;$('#peak-time').textContent=d.pull==null?'—':fmtTime(d.peakTime);$('#pasteurization').textContent=d.pasteurization<.01?'< 0.01':d.pasteurization.toFixed(d.pasteurization<10?2:1);drawChart();drawSlice();}
}
function fmtTime(s){const m=Math.round(s/60);return m>=60?`${Math.floor(m/60)}h ${m%60}m`:`${m} min`}
function setup(canvas){const dpr=devicePixelRatio||1,r=canvas.getBoundingClientRect(),w=Math.max(300,r.width),h=w*(canvas===chart?340/760:1);if(canvas.width!==Math.round(w*dpr)||canvas.height!==Math.round(h*dpr)){canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr)}const c=canvas.getContext('2d');c.setTransform(dpr,0,0,dpr,0,0);return {c,w,h}}
function drawChart(){const {c,w,h}=setup(chart),pad={l:45,r:18,t:16,b:34};c.clearRect(0,0,w,h);c.fillStyle='#faf8f3';c.fillRect(0,0,w,h);const maxT=Math.max(80,...curve.flatMap(p=>[p.core,p.probe??p.core]),currentTarget+10),maxX=Math.max(60,...curve.map(p=>p.t/60));c.strokeStyle='#ddd7ca';c.fillStyle='#777168';c.font='10px DM Mono, monospace';c.lineWidth=1;
  for(let i=0;i<=4;i++){let y=pad.t+(h-pad.t-pad.b)*i/4,temp=maxT*(1-i/4);c.beginPath();c.moveTo(pad.l,y);c.lineTo(w-pad.r,y);c.stroke();c.fillText(`${temp.toFixed(0)}°`,5,y+3)}
  for(let i=0;i<=4;i++){let x=pad.l+(w-pad.l-pad.r)*i/4;c.fillText(`${(maxX*i/4).toFixed(0)}m`,x-8,h-10)}
  const targetY=pad.t+(h-pad.t-pad.b)*(1-currentTarget/maxT);c.setLineDash([5,5]);c.strokeStyle='#e49a67';c.beginPath();c.moveTo(pad.l,targetY);c.lineTo(w-pad.r,targetY);c.stroke();c.setLineDash([]);
  if(curve.length){const path=(key,colour,dash=[])=>{c.strokeStyle=colour;c.setLineDash(dash);c.lineWidth=key==='core'?2.5:1.7;c.beginPath();curve.forEach((p,i)=>{let x=pad.l+(w-pad.l-pad.r)*(p.t/60/maxX),y=pad.t+(h-pad.t-pad.b)*(1-(p[key]??p.core)/maxT);i?c.lineTo(x,y):c.moveTo(x,y)});c.stroke();c.setLineDash([])};path('core','#b64c2b');path('probe','#315f76',[5,4]);const rest=curve.find(p=>p.phase==='rest');if(rest){let x=pad.l+(w-pad.l-pad.r)*(rest.t/60/maxX);c.strokeStyle='#6e6a61';c.setLineDash([3,4]);c.beginPath();c.moveTo(x,pad.t);c.lineTo(x,h-pad.b);c.stroke();c.setLineDash([]);c.fillText('PULL',x+5,pad.t+10)}}else{c.fillStyle='#928c81';c.font='13px Manrope';c.fillText('Run a simulation to draw the predicted coldest-point curve.',pad.l+15,h/2)}
}
function colour(t,min,max){let q=Math.max(0,Math.min(1,(t-min)/(max-min||1)));if(q<.5){let u=q*2;return [51+(226-51)*u,95+(180-95)*u,131+(92-131)*u]}let u=(q-.5)*2;return [226+(168-226)*u,180+(39-180)*u,92+(29-92)*u]}
function drawSlice(){const {c,w,h}=setup(slice);c.clearRect(0,0,w,h);c.fillStyle='#282622';c.fillRect(0,0,w,h);if(!field){c.fillStyle='#aaa49a';c.font='12px DM Mono';c.textAlign='center';c.fillText('FINAL TEMPERATURE FIELD',w/2,h/2);c.textAlign='start';return}const {n,temperature,mask}=field,z=Math.min(n-1,Math.round(+$('#slice-depth').value*(n-1))),at=(x,y)=>(x*n+y)*n+z;let min=Infinity,max=-Infinity;for(let i=0;i<temperature.length;i++)if(mask[i]){min=Math.min(min,temperature[i]);max=Math.max(max,temperature[i])}const off=document.createElement('canvas');off.width=n;off.height=n;const oc=off.getContext('2d'),im=oc.createImageData(n,n);for(let x=0;x<n;x++)for(let y=0;y<n;y++){let i=at(x,y),p=4*((n-1-y)*n+x);if(mask[i]){let rgb=colour(temperature[i],min,max);im.data[p]=rgb[0];im.data[p+1]=rgb[1];im.data[p+2]=rgb[2];im.data[p+3]=255}}oc.putImageData(im,0,0);c.imageSmoothingEnabled=false;const size=Math.min(w,h);c.drawImage(off,(w-size)/2,(h-size)/2,size,size);$('#slice-label').textContent=`${z+1} / ${n} · ${min.toFixed(1)}–${max.toFixed(1)} °C`}
$('#slice-depth').addEventListener('input',drawSlice);window.addEventListener('resize',()=>{drawChart();drawSlice()});drawChart();drawSlice();
