import './style.css';

const app=document.querySelector('#app');
app.innerHTML=`
<header><div><span class="eyebrow">3-D HEAT TRANSFER · LOCAL</span><h1>Roast Solver</h1><p>Explore an honest physics estimate—from oven to carryover.</p></div><div class="model-note">Synthetic / literature-model parameters<br><strong>Not empirically calibrated</strong></div></header>
<main>
<section class="panel controls"><h2>Cook setup</h2><form id="form">
<label>Shape preset<select name="preset"><option value="roast">Boneless roast</option><option value="bird">Whole bird + cavity</option><option value="slab">Slab</option><option value="ham">Ham</option></select></label>
<div class="row"><label>Weight <span><input name="mass" type="number" value="1.5" min="0.2" max="8" step="0.1"> kg</span></label><label>Starting temp <span><input name="initial" type="number" value="5" min="-2" max="30"> °C</span></label></div>
<div class="row"><label>Oven temp <span><input name="oven" type="number" value="180" min="60" max="260"> °C</span></label><label>Pull target <span><input name="target" type="number" value="60" min="40" max="90"> °C</span></label></div>
<div class="row"><label>Rest <span><input name="rest" type="number" value="30" min="0" max="120"> min</span></label><label>Grid<select name="resolution"><option value="26">Preview · 26³</option><option value="34" selected>Balanced · 34³</option><option value="44">Detailed · 44³</option></select></label></div>
<div class="checks"><label><input name="convection" type="checkbox"> Fan convection</label><label><input name="covered" type="checkbox"> Covered / humid</label></div>
<button id="run" type="submit">Run simulation <span>→</span></button>
</form><div class="disclaimer"><strong>Model, not thermometer.</strong> Shape and boundary conditions dominate uncertainty. Verify food temperatures with a calibrated probe.</div></section>
<section class="workspace">
<div class="panel chart-card"><div class="section-title"><div><span class="eyebrow">TEMPERATURE HISTORY</span><h2>Cold spot & pull-time probe</h2></div><span id="status" class="status idle">Ready</span></div><canvas id="chart" width="900" height="370" aria-label="Temperature history chart"></canvas><div class="legend"><span><i class="cold"></i>Instantaneous coldest</span><span><i class="probe"></i>Stable probe</span><span><i class="target"></i>Target</span></div><div class="progress"><i id="progress"></i></div></div>
<div class="lower">
<div class="panel results"><span class="eyebrow">PREDICTION</span><h2>Pull & carryover</h2><div class="metrics"><div><small>Pull at</small><strong id="pull">—</strong></div><div><small>Peak core</small><strong id="peak">—</strong></div><div><small>Carryover</small><strong id="carry">—</strong></div><div><small>Peak after pull</small><strong id="peakAt">—</strong></div></div><details><summary>Advanced pasteurization output</summary><p>Equivalent minutes at 70°C, z = 7°C, evaluated at the modeled coldest cell:</p><strong id="dose">—</strong><p class="fine">A model integral is not a safety certification. Pathogen, handling, and measurement assumptions matter.</p></details></div>
<div class="panel slice-card"><div class="section-title"><div><span class="eyebrow">DONENESS FIELD</span><h2>Center slice</h2></div><span id="gridMeta">—</span></div><canvas id="slice" width="400" height="400" aria-label="Final center temperature slice"></canvas><div class="scale"><span>cool</span><i></i><span>hot</span></div></div>
</div></section></main><footer>Roast Solver M6 · Runs entirely in your browser · No data uploaded</footer>`;

const $=s=>document.querySelector(s), chart=$('#chart'), sliceCanvas=$('#slice');
let worker, latest={times:[],cold:[],probe:[]};
function fitCanvas(c,ratio=2){const r=c.getBoundingClientRect();const w=Math.max(10,Math.floor(r.width*ratio)),h=Math.max(10,Math.floor(r.height*ratio));if(c.width!==w||c.height!==h){c.width=w;c.height=h}}
function drawChart(data=latest){fitCanvas(chart);const c=chart.getContext('2d'),w=chart.width,h=chart.height,p={l:80,r:30,t:24,b:55};c.clearRect(0,0,w,h);c.fillStyle='#111614';c.fillRect(0,0,w,h);const times=Array.from(data.times||[]), vals=[...Array.from(data.cold||[]),...Array.from(data.probe||[])];let xmax=Math.max(3600,...times), ymin=Math.min(0,...vals),ymax=Math.max(100,+new FormData($('#form')).get('oven'),...vals);ymax=Math.min(ymax,220);const X=x=>p.l+x/xmax*(w-p.l-p.r),Y=y=>h-p.b-(y-ymin)/(ymax-ymin)*(h-p.t-p.b);c.strokeStyle='#34413c';c.fillStyle='#8e9b95';c.font='24px system-ui';c.lineWidth=2;for(let i=0;i<=4;i++){let y=ymin+(ymax-ymin)*i/4;c.beginPath();c.moveTo(p.l,Y(y));c.lineTo(w-p.r,Y(y));c.stroke();c.fillText(`${Math.round(y)}°`,12,Y(y)+8)}for(let i=0;i<=4;i++){let x=xmax*i/4;c.fillText(`${(x/3600).toFixed(1)}h`,X(x)-20,h-14)}let target=+new FormData($('#form')).get('target');c.setLineDash([12,9]);c.strokeStyle='#db9b55';c.beginPath();c.moveTo(p.l,Y(target));c.lineTo(w-p.r,Y(target));c.stroke();c.setLineDash([]);function line(v,color){if(!times.length)return;c.strokeStyle=color;c.lineWidth=5;c.beginPath();Array.from(v).forEach((y,i)=>{let fn=i?'lineTo':'moveTo';c[fn](X(times[i]),Y(y))});c.stroke()}line(data.cold,'#68c7b5');line(data.probe,'#f2eee5')}
function heatColor(t,min,max){let q=Math.max(0,Math.min(1,(t-min)/(max-min||1)));let stops=[[22,37,45],[45,127,135],[224,169,87],[185,67,45]];let x=q*(stops.length-1),i=Math.min(stops.length-2,Math.floor(x)),f=x-i;return stops[i].map((v,j)=>Math.round(v+(stops[i+1][j]-v)*f))}
function drawSlice(raw,n){fitCanvas(sliceCanvas,1.5);const c=sliceCanvas.getContext('2d'), img=document.createElement('canvas');img.width=n;img.height=n;const x=img.getContext('2d'),d=x.createImageData(n,n),finite=Array.from(raw).filter(Number.isFinite),lo=Math.min(...finite),hi=Math.max(...finite);for(let i=0;i<raw.length;i++){let o=i*4;if(Number.isFinite(raw[i])){let rgb=heatColor(raw[i],lo,hi);d.data.set([...rgb,255],o)}else d.data.set([12,17,15,255],o)}x.putImageData(d,0,0);c.imageSmoothingEnabled=false;c.clearRect(0,0,sliceCanvas.width,sliceCanvas.height);c.drawImage(img,0,0,sliceCanvas.width,sliceCanvas.height);c.fillStyle='#fff';c.font='20px system-ui';c.fillText(`${lo.toFixed(1)}–${hi.toFixed(1)} °C`,14,sliceCanvas.height-14)}
function fmtTime(sec){if(!(sec>=0))return 'Not reached';let h=Math.floor(sec/3600),m=Math.round((sec-h*3600)/60);return h?`${h}h ${m}m`:`${m} min`}
function start(params){if(worker)worker.terminate();worker=new Worker(new URL('./solver.worker.js',import.meta.url),{type:'module'});$('#status').textContent='Starting WASM…';$('#status').className='status running';$('#run').disabled=true;$('#progress').style.width='1%';worker.onmessage=({data})=>{if(data.type==='error'){fail(data.message);return}if(data.type==='progress'){latest=data;drawChart();$('#status').textContent=data.phase;$('#progress').style.width=`${Math.max(2,data.progress*100)}%`}if(data.type==='done'){latest=data;drawChart();drawSlice(data.slice,data.n);finish(data)}};worker.onerror=e=>fail(e.message);worker.postMessage({type:'run',params})}
function finish(d){$('#status').textContent='Complete';$('#status').className='status done';$('#run').disabled=false;$('#progress').style.width='100%';let times=Array.from(d.times),probe=Array.from(d.probe),pull=d.pull,reached=pull>=0,index=reached?times.findIndex(t=>t>=pull):-1,post=reached?probe.slice(index):probe.slice(-1),peak=Math.max(...post),peakIndex=probe.indexOf(peak);$('#pull').textContent=fmtTime(pull);$('#peak').textContent=`${peak.toFixed(1)}°C`;$('#carry').textContent=reached?`+${Math.max(0,peak-probe[index]).toFixed(1)}°C`:'—';$('#peakAt').textContent=reached?fmtTime(times[peakIndex]-pull):'—';let dose=Array.from(d.dose);$('#dose').textContent=`${dose.at(-1).toFixed(2)} equivalent min`;$('#gridMeta').textContent=`${d.n}³ · ${(d.dx*1000).toFixed(1)} mm`}
function fail(msg){$('#status').textContent='Error';$('#status').className='status error';$('#run').disabled=false;console.error(msg);alert(`Simulation failed: ${msg}`)}
$('#form').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget),p=Object.fromEntries(f);p.convection=f.has('convection');p.covered=f.has('covered');start(p)});new ResizeObserver(()=>drawChart()).observe(chart);drawChart();
